### ISSUE TITLE
feat: In skore UI view, be able to write a Markdown item

### ISSUE THREAD

**Issue by sylvaincom** [probabl-ai/skore#1022]
### Is your feature request related to a problem? Please describe.

*Got this issue from a user interview.*

As a data scientist, I would like to be able to add some Markdown text in the skore UI to give more context in my reports.

We have a skore UI with a reporting feature (a view). Hence, the user can add some items such as plots in a view, but can not write some Markdown text directly from the UI, for example to comment them or add some narration about what is going on. Our pitch is that users can write nice reports with skore UI, but for now (v0.5) they can not write comments, which is problematic.

### Describe the solution you'd like

In the skore UI, I would like to be able to add Markdown text cells. For example, I want to add some comments on a plot, add a title, or add some narrative comments between items such as "Now, let us look into some preprocessing". It is to possible to add a Markdown text cell, then to edit and delete it for example.

### Describe alternatives you've considered, if relevant

This issue is to add some Markdown text items directly from the skore UI. *In addition* to this, a counterpart would be to be able to add some Markdown text from the Python API. This is currently feasible, but the `put` is quite heavy as it is done from a code cell while, in a Jupyter notebook, I often already have some narrative comments in markdown cells (and not code cells). This is related to https://github.com/probabl-ai/skore/issues/422 where @glemaitre was suggesting to be able to `put` a markdown cell directly from a Jupyter notebook to the UI.

### Additional context

Note that this is not annotating the version of an item as done in #1041, this is adding some narrative comments as a text skore item.

*EDIT on 2024-01-15*

Get inspiration from what exists in Jupyter Notebook in VS Code (data scientists are used to working like this):
- You can add a markdown cell *at the location that you want* with a `+ Markdown` button.
- When editing a Markdown cell,
    - there is no "modale" that appears, it is inline ; so that users can comment in markdown the python code that is displayed just above (the users can see with their eyes what they are currently commenting).
    - inside the cell, you have the raw markdown `*italic*` and outside the cell you have the rendering *italic*
- You can go "in" (with `Enter` or double-click) and "out" of a markdown cell (`Shift+Enter`).

https://github.com/user-attachments/assets/9e672691-5093-4b29-a9ab-6979d2c24eb0

### Ready Checklist

- [x] Design specification approved (by @tuscland and @MarieS-WiMLDS)
- [ ] Technical specification approved
- [ ] Critical considerations addressed
- [ ] (Optional) Planning requirements met

**Comment by sylvaincom** [comment]
If I remember correctly, on a related topic, @glemaitre was also suggesting to be able to `put` a markdown cell directly from a notebook to the UI

**Comment by MarieS-WiMLDS** [comment]
Isn't it a way to access to this: https://github.com/probabl-ai/skore/issues/905?

**Comment by sylvaincom** [comment]
Yes, it is very closely related, we let both issue live?

**Comment by anasstarfaoui** [comment]
I feel like this task is very related to this one isn't it ? 

https://github.com/probabl-ai/skore/issues/1041

**Comment by sylvaincom** [comment]
@anasstarfaoui following our quick call, I just added a paragraph in the above issue in "Additional context"

**Comment by MarieS-WiMLDS** [comment]
removing this from the milestone, as we plan to hide skore-ui.

**Comment by anasstarfaoui** [comment]
https://github.com/user-attachments/assets/46f13a8f-4a25-4d6c-b785-02f1933859cf

So here is the final flow!


Let me know if it's okay for you @sylvaincom @rouk1 @MarieS-WiMLDS

**Comment by MarieS-WiMLDS** [comment]
It's looking good! thanks Anass :) !  
It would be great to have some kind of titles, like in markdown, thanks to `#`. Will it be possible? (more a tech question for @rouk1)

**Comment by sylvaincom** [comment]
LGTM thanks!

**Comment by anasstarfaoui** [comment]
Hello, you're both absolutely right. I added it in the latest version!

![Image](https://github.com/user-attachments/assets/10f43fce-5014-44f7-b91c-76241744e095)

**Comment by rouk1** [comment]
Implementation PR is running here: #1234

**Comment by rouk1** [comment]
As discussed all the view section is to be removed.
I'm hence closing this as not planned (anymore^^)
