### ISSUE TITLE
Tone and Text Refinement

### ISSUE THREAD

**Issue by anasstarfaoui** [probabl-ai/skore#480]
**Description:**
The current language and tone of Skore can be too technical and formal for non-technical users. Simplifying the tone and text will make the platform more approachable.

**User Story:**
As a user, I want clear, concise, and friendly language in Skore, so that I can understand and engage with the platform more easily.

**Acceptance Criteria:**

- [ ] All technical jargon is simplified or clarified.
- [ ] Instructions and tooltips are rewritten in a friendly and approachable tone.
- [ ] Error messages are descriptive but approachable.

**Comment by tuscland** [comment]
Is this epic aimed at improving the score once, or is it an ever-desirable property?

**Comment by anasstarfaoui** [comment]
Both, we need a fix for today version and a long term reflexion on tone we want to implement in skore/ensembl

**Comment by anasstarfaoui** [comment]
Here is a start for this, we need to see that only as a basis for reflexion.

Let me know what do you think: https://www.notion.so/probabl/Tone-UX-writing-12def76d36b9805abd37c9f8f23870e0?pvs=4

**Comment by tuscland** [comment]
Matt and I made some feedback

**Comment by tuscland** [comment]
Closing in favor of a workshop to define a policy.
