### ISSUE TITLE
feat: Record each value of an item over time (history)

### ISSUE THREAD

**Issue by thomass-dev** [probabl-ai/skore#504]
## Functional description

We have seen that for new features, such as cross-validation, we want to aggregate metrics over time.

We want to offer a way to save all updates to an item. This means saving items in an "appending" rather in "overriding" mode.
In this way, we can retain all the values of an item over time.

This feature would enable the following benefits:
- The user is confident they will not lose saved information
- The user has access to past item values
- The user can compare items
- This feature would open potential user feedback and discussion on the wider topic of tracking the evolution of results without having to code complex features

## UI/UX requirements

- visible and discoverable UI for navigating through item updates
- navigate easily through all existing updates of items (e.g. back and next buttons)
- when an item has no history, updates navigation is not visible or disabled, and we only see the creation date "Added on 2024-10-21 at 12:35:50 CET -> use browser's locale formats for date and time formatting).
- when an item has history, updates navigation is visible or active, and we see the last update date "Last updated on 2024-10-22 at 17:12:58 CET -> use browser's locale formats for date and time formatting)

## Future evolutions

The user can switch between punctual or historicized view.
This could work for:
- primitive numbers: plot the evolution of the value
- cross validation: display a historicized view of the cross validation runs (scatter plot with error bar)

---

## Technical Proposition: 5 phases

1. Change the way items are saved without breaking any API (project or UI).

2. Add a new endpoint (2.1) to retrieve all the values of an item from back-end to front-end.
Add a new selection button on widgets allowing to switch from one version to another ( reference @rouk1 ), using this last endpoint.

    We should think how to intelligibly represent all the versions of an item in this button: do we display only the date of the item, its content, etc.

    (2.1) `/item/<key>?<latest=true|false>`.
This new endpoint has a positional `<key>` parameter and returns, depending on a optional parameter `<latest>`, the latest version of the item, or all its versions.

3. Add a new developer API inside the project one, to browse programmatically all the versions of an item. 
I propose to add an new `ItemProxy` component, returned by `project.get_item`, which looks something like: 

```python
class ItemProxy:
    def latest() -> Item: ...
    def all() -> list[Item]: ...
```

4. Kill `diskcache` to efficiently browse the different versions of an item using SQL-like language.

5. Add a pruning system.

Related to #403 

## UI/UX solution

See [mockups](https://www.figma.com/design/Qzjyxv0lPDU2kKtsH9dcp3/Skore---Workstation---High-fidelity-mock-ups---Q3?node-id=4327-8263&t=Ahj0xh4mwqSMHFiW-1).

With the following adjustments:
- display history in the "More/Browse History" menu of an Item.
- when an old item is displayed, a text alerts the user: "⚠ You are viewing an old update (switch to latest)"

----
### Ready State Checklist

- [x] https://github.com/probabl-ai/skore/issues/568
- [x]  Specification complete and validated
- [x]  All implementation prerequisites met
- [x]  Priority assigned
- [x]  Team reviewed and approved
- [x] #666
- [ ]  Effort estimated (optional)

**Comment by rouk1** [comment]
Without stepping on toes of @anasstarfaoui I would recommend something simple to start.
Icon to be refined (used [that one](https://thenounproject.com/icon/history-5831078/)).
![history](https://github.com/user-attachments/assets/d15ff7c4-c656-431a-824f-d865a9109e8d)

**Comment by tuscland** [comment]
@rouk1 please explain how this solution caters to the user's needs.

**Comment by rouk1** [comment]
It's a proposal for a first step that is easy to implement in the current design.

**Comment by tuscland** [comment]
Let's discuss this at the workshop on Monday.

**Comment by tuscland** [comment]
The discussion led to the following changes:

- we completed the issue description with functional requirements
- created an issue for @anasstarfaoui to design the UI/UX
- we added a "ready state checklist"
- the `epic` label was applied
- notified @thomass-dev to update the technical requirements

**Comment by augustebaum** [comment]
After discussion with @thomas, here are a few things to add/modify:
- currently the interface is `dict[key, Item]`; in the first iteration the interface should change to `dict[key, list[Item]]` (to modify the internals as little as possible)
- relatedly, `Project.delete` should delete the whole list of Items related to a key.
- phases 4 and 5 are low priority and should not be considered mandatory to complete this feature
- the term `ItemProxy` is in reference to the SQLAlchemy API; I'm not familiar with SQLAlchemy, so the name initially threw me off. We should either find a better name (Django uses `Manager`, not sure if that's better) or be very explicit that this is the reason, e.g. by linking to the SQLAlchemy docs.

**Comment by rouk1** [comment]
Could we discuss the API proposal ? 
The current proposal suggest that adding a query parameter will output a scalar instead of the default list. It's always easier to handle a consistent data structure.

To keep frontend implementation simple I would recommend to update the `project/items` endpoint.
For now it returns a hash of items. Items respects the following interface.

```ts
interface ProjectItem {
  media_type: string;
  value: any;
  updated_at: string;
  created_at: string;
}
```

I would recommend to update the endpoint so that it returns a hash of project item history by key.  Interface could look like:

```ts
interface ProjectItem {
  id: number;
  media_type: string;
  value: any;
  updated_at: string;
  created_at: string;
}

interface ProjectItemHistory {
  latest: ProjectItem;
  previous_ids: number[];
}
```

Then we could enhance the project items endpoint to follow a list detail pattern.

`GET` `/api/project/items` returns all the project items history hashed by there keys.
`GET` `/api/project/items/<id>` returns a specific item by it's id.

This approach will trigger one API call to items at each polling round. And calls to detail API will only be done when needed.
Note that depending on how we want to display versioned items (by date, id, ??) we may need to create some kind of preview instead of a list of ids.

**Comment by thomass-dev** [comment]
> 3. Add a new developer API inside the project one, to browse programmatically all the versions of an item. 
> I propose to add an new `ItemProxy` component, returned by `project.get_item`, which looks something like: 
> 
> ```python
> class ItemProxy:
>     def latest() -> Item: ...
>     def all() -> list[Item]: ...
> ```

Adding a dedicated proxy to `Item` is quite complex because we should keep a reference to the persistence to get the item's values when the user call retrieval functions. The logic of how to get/put an item from/to the persistence shouldn't be spread outside the repository.

We choose instead to add a function directly in the Items repository `get_items`, so that the user can't directly interact with persistence.

```python
class ItemRepository:
    def get(key) -> Any: ...
    def get_item(key) -> Item: ...
    def get_items(key) -> list[Item]: ...
```

**Comment by thomass-dev** [comment]
State of the issue: using `diskcache`, we save all the versions of an item in the back-end, and send all these versions to the front-end.

We fix the front-end to used only the latest version of an item, to be retro-compatible.
We now need to implement stories designed by @anasstarfaoui in the front-end.

**Comment by tuscland** [comment]
Updated the description with UI/UX implementation details.

**Comment by rouk1** [comment]
Indeed the full feature is available for a functional review.
Ping @MarieS-WiMLDS, @sylvaincom

**Comment by MarieS-WiMLDS** [comment]
yep, this epic is done! I spotted two small issue while preparing for a release, will do dedicated tickets :)
