### ISSUE TITLE
fix(docs): Improve documentation v3

### ISSUE THREAD

**Issue by sylvaincom** [probabl-ai/skore#627]
Following https://github.com/probabl-ai/skore/pull/618, here are the next improvements for the documentation:
- [ ] https://github.com/probabl-ai/skore/issues/616
- [ ] https://github.com/probabl-ai/skore/issues/625
- [ ] https://github.com/probabl-ai/skore/issues/626

**Comment by sylvaincom** [comment]
Closed by PR https://github.com/probabl-ai/skore/pull/636 and PR https://github.com/probabl-ai/skore/pull/646

Follow-up epic issue: https://github.com/probabl-ai/skore/issues/649
