### ISSUE TITLE
fix(docs): Improve documentation v4

### ISSUE THREAD

**Issue by sylvaincom** [probabl-ai/skore#649]
Following PR https://github.com/probabl-ai/skore/pull/636 that closed issue https://github.com/probabl-ai/skore/issues/627, here are the next improvements of the documentation:

### P1
- [x] https://github.com/probabl-ai/skore/issues/796
- [x] #779
- [x] #775
- [x] #776
- [x] https://github.com/probabl-ai/skore/issues/799

### P2
- [x] https://github.com/probabl-ai/skore/issues/625
- [x] https://github.com/probabl-ai/skore/issues/662
- [x] https://github.com/probabl-ai/skore/issues/676

**Comment by sylvaincom** [comment]
Closing this epic but letting https://github.com/probabl-ai/skore/issues/675 live as its own issue
