### ISSUE TITLE
fix(docs): Improve the API

### ISSUE THREAD

**Issue by sylvaincom** [probabl-ai/skore#761]
Our [API](https://probabl-ai.github.io/skore/latest/api.html) needs to be updated.
Waiting on an internal workshop to discuss what is to be expected from the documentation and who will do it.

Issues:
- [ ] https://github.com/probabl-ai/skore/issues/734
- [ ] https://github.com/probabl-ai/skore/issues/735
- [ ] https://github.com/probabl-ai/skore/issues/736
- [ ] https://github.com/probabl-ai/skore/issues/738

**Comment by sylvaincom** [comment]
This isn't an "epic" anymore, closing this while letting https://github.com/probabl-ai/skore/issues/734 and https://github.com/probabl-ai/skore/issues/736 live seperately
