### ISSUE TITLE
fix(docs): Add instructions to install skore using conda

### ISSUE THREAD

**Issue by sylvaincom** [probabl-ai/skore#919]
### Context

Thanks to @glemaitre and following https://github.com/conda-forge/staged-recipes/pull/28209, skore is now downloadable from conda.

We have this new repository: https://github.com/conda-forge/skore-feedstock

And at each release, we need to make a branch, bump the version to build the conda-forge binary, and then once we merge, everybody can download skore from conda-forge

The feedstock is now up: https://anaconda.org/conda-forge/skore

### TODO

- [ ] check if installing from conda works well
- [ ] add instructions for installation in the README and in the doc in `sphinx/install.rst` (it should be just `conda install conda-forge::skore` I guess)
- [ ] decide who will do the bumping to conda-forge each time

**Comment by augustebaum** [comment]
Should there be a badge like we have for PyPI?

**Comment by augustebaum** [comment]
> decide who will do the bumping to conda-forge each time

We might use a GitHub Action to do this automatically like we do for PyPI. See for example https://github.com/marketplace/actions/publish-conda-forge. In any case I think this can become a separate issue.

**Comment by glemaitre** [comment]
> We might use a GitHub Action to do this automatically like we do for PyPI. See for example https://github.com/marketplace/actions/publish-conda-forge. In any case I think this can become a separate issue.

Be aware that `conda-forge` should already have a bot that detect a new version on PyPI and will open a PR on the `skore-feedstock`. It might sometimes be faster to just make a branch from your fork and just change the version number and SHA256 (and adapt the dependencies if necessary). Anyone listed as a maintainer can create the release there and anyone listed can add a new maintainer.
